import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { assertPathInside } from "@/lib/security/safe-path";
import type { RecoveryRecord } from "@/lib/types";
import { getRecoveryModPath } from "@/lib/zomboid/paths";

const MOD_INFO = `name=Zomboid Save Manager Recovery
id=ZomboidSaveManagerRecovery
description=One-shot local character health recovery prepared by ZSM.
poster=
`;

function luaString(value: string): string {
  return JSON.stringify(value);
}

export function buildRecoveryLua(
  recovery: Pick<RecoveryRecord, "id" | "characterName">,
  saveName: string,
): string {
  return `-- Generated by Zomboid Save Manager. One-shot recovery only.
local recoveryId = ${luaString(recovery.id)}
local targetCharacter = ${luaString(recovery.characterName)}
local targetWorld = ${luaString(saveName)}
local appliedKey = "ZSM_RECOVERY_" .. recoveryId

local function matchesTarget(player)
    if not player then return false end
    local world = getWorld()
    if not world or world:getWorld() ~= targetWorld then return false end
    return player:getFullName() == targetCharacter
end

local function applyRecovery(playerNum, player)
    if not matchesTarget(player) then return end

    local modData = player:getModData()
    if modData[appliedKey] then
        Events.OnCreatePlayer.Remove(applyRecovery)
        return
    end

    local bodyDamage = player:getBodyDamage()
    if not bodyDamage then
        print("ZSM_RECOVERY_FAILED|" .. recoveryId .. "|NO_BODY_DAMAGE")
        return
    end

    bodyDamage:RestoreToFullHealth()
    bodyDamage:setOverallBodyHealth(100)
    bodyDamage:setInfected(false)
    bodyDamage:setInfectionLevel(0)
    bodyDamage:setInfectionTime(-1)
    bodyDamage:setIsFakeInfected(false)
    bodyDamage:setFakeInfectionLevel(0)

    local bodyParts = bodyDamage:getBodyParts()
    for index = 0, bodyParts:size() - 1 do
        local bodyPart = bodyParts:get(index)
        bodyPart:RestoreToFullHealth()
        bodyPart:SetInfected(false)
        bodyPart:setInfectedWound(false)
        bodyPart:setWoundInfectionLevel(-1)
    end

    modData[appliedKey] = true
    print("ZSM_RECOVERY_COMPLETE|" .. recoveryId)
    Events.OnCreatePlayer.Remove(applyRecovery)
end

local function applyOnGameStart()
    applyRecovery(0, getPlayer())
end

Events.OnCreatePlayer.Add(applyRecovery)
Events.OnGameStart.Add(applyOnGameStart)
`;
}

export async function installRecoveryScript(
  recovery: Pick<RecoveryRecord, "id" | "characterName">,
  saveName: string,
  modRoot = getRecoveryModPath(),
): Promise<void> {
  const lua = buildRecoveryLua(recovery, saveName);
  const versionRoots = [modRoot, path.join(modRoot, "42")];

  for (const versionRoot of versionRoots) {
    const luaDirectory = path.join(versionRoot, "media", "lua", "client");
    const infoPath = path.join(versionRoot, "mod.info");
    const luaPath = path.join(luaDirectory, "ZSMRecovery.lua");
    assertPathInside(modRoot, infoPath);
    assertPathInside(modRoot, luaPath);
    await mkdir(luaDirectory, { recursive: true });
    await Promise.all([
      writeFile(infoPath, MOD_INFO, "utf8"),
      writeFile(luaPath, lua, "utf8"),
    ]);
  }
}

export async function disableRecoveryScript(
  recoveryId: string,
  modRoot = getRecoveryModPath(),
): Promise<void> {
  const versionRoots = [modRoot, path.join(modRoot, "42")];
  for (const versionRoot of versionRoots) {
    const luaPath = path.join(
      versionRoot,
      "media",
      "lua",
      "client",
      "ZSMRecovery.lua",
    );
    assertPathInside(modRoot, luaPath);
    try {
      const current = await readFile(luaPath, "utf8");
      if (current.includes(recoveryId)) {
        await writeFile(
          luaPath,
          "-- Recovery completed or rolled back. No pending operation.\n",
          "utf8",
        );
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
  }
}
