import type { RecoveryRecord } from "@/lib/types";

export const RECOVERY_MOD_INFO = `name=Zomboid Save Manager Recovery
id=ZomboidSaveManagerRecovery
description=One-shot local character health recovery prepared by ZSM.
poster=
`;

function luaString(value: string): string {
  return JSON.stringify(value);
}

export function buildRecoveryLua(
  recovery: Pick<RecoveryRecord, "id" | "characterName">,
  saveName: string,
): string {
  return `-- Generated by Zomboid Save Manager. One-shot recovery only.
local recoveryId = ${luaString(recovery.id)}
local targetCharacter = ${luaString(recovery.characterName)}
local targetWorld = ${luaString(saveName)}
local appliedKey = "ZSM_RECOVERY_" .. recoveryId

local function matchesTarget(player)
    if not player then return false end
    local world = getWorld()
    if not world or world:getWorld() ~= targetWorld then return false end
    return player:getFullName() == targetCharacter
end

local function applyRecovery(playerNum, player)
    if not matchesTarget(player) then return end

    local modData = player:getModData()
    if modData[appliedKey] then
        Events.OnCreatePlayer.Remove(applyRecovery)
        return
    end

    local bodyDamage = player:getBodyDamage()
    if not bodyDamage then
        print("ZSM_RECOVERY_FAILED|" .. recoveryId .. "|NO_BODY_DAMAGE")
        return
    end

    bodyDamage:RestoreToFullHealth()
    bodyDamage:setOverallBodyHealth(100)
    bodyDamage:setInfected(false)
    bodyDamage:setInfectionLevel(0)
    bodyDamage:setInfectionTime(-1)
    bodyDamage:setIsFakeInfected(false)
    bodyDamage:setFakeInfectionLevel(0)

    local bodyParts = bodyDamage:getBodyParts()
    for index = 0, bodyParts:size() - 1 do
        local bodyPart = bodyParts:get(index)
        bodyPart:RestoreToFullHealth()
        bodyPart:SetInfected(false)
        bodyPart:setInfectedWound(false)
        bodyPart:setWoundInfectionLevel(-1)
    end

    modData[appliedKey] = true
    print("ZSM_RECOVERY_COMPLETE|" .. recoveryId)
    Events.OnCreatePlayer.Remove(applyRecovery)
end

local function applyOnGameStart()
    applyRecovery(0, getPlayer())
end

Events.OnCreatePlayer.Add(applyRecovery)
Events.OnGameStart.Add(applyOnGameStart)
`;
}
